name: Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '48 3 * * *'

env:
  owner: gbxyz

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - version: 8.2
            tag: gbxyz/openswoole:php82
          - version: 8.3
            tag: gbxyz/openswoole:php83

    steps:
      - uses: actions/checkout@v3

      - name: Log in
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: gbxyz
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{matrix.tag}}
          build-args: PHP_VERSION=${{matrix.version}}
